### ISSUE TITLE
安装报错 PermissionError: [Errno 13] Permission denied: '/config/portal'

### ISSUE THREAD

**Issue by uniquejava** [wise2c-devops/build-harbor-aarch64#10]
Hello, 可以帮忙看看为什么出错吗, 我用了sudo也不行.  

Apple M2芯片

```sh
➜  sudo ./install.sh

[Step 0]: checking if docker is installed ...

Note: docker version: 27.1.1

[Step 1]: checking docker-compose is installed ...

Note: Docker Compose version v2.29.1

[Step 2]: loading Harbor images ...
Loaded image: goharbor/redis-photon:v2.13.0-aarch64
Loaded image: goharbor/harbor-redis-base:v2.13.0-aarch64
Loaded image: goharbor/trivy-adapter-photon:v2.13.0-aarch64
Loaded image: goharbor/harbor-trivy-adapter-base:v2.13.0-aarch64
Loaded image: goharbor/registry-photon:v2.13.0-aarch64
Loaded image: goharbor/harbor-jobservice-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-core-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-exporter-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-registry-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-nginx-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-log-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-portal:v2.13.0-aarch64
Loaded image: goharbor/harbor-portal-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-db-base:v2.13.0-aarch64
Loaded image: goharbor/prepare:v2.13.0-aarch64
Loaded image: goharbor/harbor-registryctl:v2.13.0-aarch64
Loaded image: goharbor/harbor-registryctl-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-jobservice:v2.13.0-aarch64
Loaded image: goharbor/harbor-db:v2.13.0-aarch64
Loaded image: goharbor/harbor-prepare-base:v2.13.0-aarch64
Loaded image: goharbor/harbor-exporter:v2.13.0-aarch64
Loaded image: goharbor/nginx-photon:v2.13.0-aarch64
Loaded image: goharbor/harbor-log:v2.13.0-aarch64
Loaded image: goharbor/harbor-core:v2.13.0-aarch64


[Step 3]: preparing environment ...

[Step 4]: preparing harbor configs ...
prepare base dir is set to /Users/cyper/bin/harbor
WARNING:root:WARNING: HTTP protocol is insecure. Harbor will deprecate http protocol in the future. Please make sure to upgrade to https
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/commands/prepare.py", line 41, in prepare
    prepare_portal(config_dict)
  File "/usr/src/app/utils/portal.py", line 10, in prepare_portal
    prepare_dir(portal_config_dir, uid=DEFAULT_UID, gid=DEFAULT_GID)
  File "/usr/src/app/utils/misc.py", line 87, in prepare_dir
    recursive_chown(absolute_path, uid, gid)
  File "/usr/src/app/utils/misc.py", line 107, in recursive_chown
    os.chown(path, uid, gid)
PermissionError: [Errno 13] Permission denied: '/config/portal'
```

yaml我修改的地方

```yaml
hostname: harbor.local  # 或你的域名
http:
  port: 12346         # 默认为80
harbor_admin_password: Harbor12345  # 管理员密码
data_volume: /Users/cyper/data/harbor  # 默认为/data

log:
  # options are debug, info, warning, error, fatal
  level: info
  # configs for logs in local storage
  local:
    # Log files are rotated log_rotate_count times before being removed. If count is 0, old versions are removed rather than rotated.
    rotate_count: 0
    # Log files are rotated only if they grow bigger than log_rotate_size bytes. If size is followed by k, the size is assumed to be in kilobytes.
    # If the M is used, the size is in megabytes, and if G is used, the size is in gigabytes. So size 100, size 100k, size 100M and size 100G
    # are all valid.
    rotate_size: 10M
    # The directory on your host that store log
    #location: /var/log/harbor
    location: /tmp/harbor_logs
```
